spring.application.name=MagicFridgeAI

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:magicfridgeai
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=magic
spring.datasource.password=fridge

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

chatgpt.url=https://api.openai.com/v1/chat/completions
chatgpt.model=gpt-4o-mini
api.key=${API_KEY:}
